### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by tmcw** [geojson-xyz/geojson-xyz-data#1]
@iandees

Want to take a look at this sketch and let me know what should change before solidifying a first pass at a metadata scheme? This is very hacked-together right now, but to give some background:
- Complete metadata for all data sources should fit into memory comfortably
- xyz should favor 'bread and butter' datasources rather than trying to get all data
- Data should be web-mappable: I'm thinking something like a limit of 5mb
- I think we should have an expectation that all individual GeoJSON files that are gettable are available as simple GET endpoints, whether on github pages, s3, or another server: no other protocols.

**Comment by iandees** [comment]
This makes sense to me. I like the curated approach and especially the guidelines for smallness/GET.
